var imgData = {
  1: [
    "images/captcha/us/1.png",
    "images/captcha/us/2.jpg",
    "images/captcha/us/3.png",
    "images/captcha/us/4.jpg",
    "images/captcha/us/5.jpeg",
    "images/captcha/us/6.png",
    "images/captcha/us/7.jpg",
    "images/captcha/us/8.jpg",
    "images/captcha/us/9.jpg",
    "us",
  ],
  2: [
    "images/captcha/rhinos/1.jpg",
    "images/captcha/rhinos/2.jpg",
    "images/captcha/rhinos/3.jpg",
    "images/captcha/rhinos/4.jpg",
    "images/captcha/rhinos/5.jpg",
    "images/captcha/rhinos/6.jpg",
    "images/captcha/rhinos/7.jpg",
    "images/captcha/rhinos/8.jpg",
    "images/captcha/rhinos/9.jpg",
    "rhinos"
  ],
  3: [
    "images/captcha/hydrants/1.jpg",
    "images/captcha/hydrants/2.jpg",
    "images/captcha/hydrants/3.jpg",
    "images/captcha/hydrants/9.jpg",
    "images/captcha/hydrants/4.jpg",
    "images/captcha/hydrants/8.jpg",
    "images/captcha/hydrants/5.jpg",
    "images/captcha/hydrants/6.jpg",
    "images/captcha/hydrants/7.jpg",
    "fire hydrants"
  ],
  4: [
    "images/captcha/trains/1.jpg",
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/6.jpg",
    "images/captcha/trains/7.jpg",
    "trains"
  ],
  5: [
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/1.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/7.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/6.jpg",
    "boats"
  ],
  6: [
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/6.jpg",
    "images/captcha/trains/7.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/1.jpg",
    "busses"
  ],
};
